### Get all categories
GET http://localhost:3000/api/categories
Accept: application/json
X-API-Key: 12345

### Create New Category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
X-API-Key: 12345

{
  "name": "Gadget"
}

### Get Category
GET http://localhost:3000/api/categories/1
Accept: application/json
X-API-Key: 12345

### Update Category
PUT http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json
X-API-Key: 12345

{
  "name": "Food"
}

### Delete Category
DELETE http://localhost:3000/api/categories/1
Accept: application/json
X-API-Key: 12345